### ISSUE TITLE
Using package in yarn project gives error

### ISSUE THREAD

**Issue by Poorva17** [5SSS/react-json-view-compare#22]
Hello, this library is really good. I am interested in using it in my yarn project. When I try to hook this component in my project it gives following error. Is there any workaround?

```
TypeError: Class constructor ServeCommand cannot be invoked without 'new'
    at runWhenInstalled (<path>/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
    at <path>/node_modules/webpack-cli/bin/utils/prompt-command.js:124:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Poorva17** [comment]
It was due to different webpack versions on path.
